[package]
name = "nfc-jukebox"
version = "0.5.0"
edition = "2021"

[dependencies]
dotenvy = { git = "https://github.com/allan2/dotenvy.git", branch = "master" }
rand = "0.8.5"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.134"
