[package]
name = "nfc-jukebox"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.134"
dotenvy = { git = "https://github.com/allan2/dotenvy.git", branch = "master" }
